-- =============================================================================
-- Seed 45 mess members — single-shot SQL
--
-- Run the entire file in the Supabase SQL Editor. No migrations to apply,
-- no Edge Function to deploy, no CSV to upload, no extension required.
-- The script:
--
--   1. Uses a pre-computed bcrypt cost-10 hash of the temporary password
--      ("Welcome123!"). The hash is pasted in as a literal so this script
--      does not depend on pgcrypto being installed in the SQL Editor's
--      search path (some Supabase projects don't have it).
--   2. INSERTs one row into auth.users per member with:
--        - email                = '<service_no>@<email_dom>'   (placeholder)
--        - email_confirmed_at   = now()                         (no confirmation link)
--        - encrypted_password   = bcrypt('Welcome123!')
--        - raw_user_meta_data   = { service_number, full_name, rank }
--   3. Immediately INSERTs the matching public.users + public.members rows
--      (does NOT rely on the AFTER INSERT trigger from migration 0015).
--   4. Prints a results grid in the editor: service_number, email, status,
--      user_id, message.
--
-- Idempotency:
--   - Rows whose service_number already exists in public.users (active) are
--     skipped — they appear in the report as 'skipped_active'.
--   - Re-running the script does not duplicate anything.
--
-- Members sign in at /login with:
--   service_number : e.g. 5083
--   password       : Welcome123!
-- They can change their password from /portal/profile after signing in.
-- They can set their real email later from /portal/profile (or via the
-- set-member-email Edge Function — optional).
-- =============================================================================

set search_path = public;

-- Pre-computed bcrypt cost-10 hash of 'Welcome123!'. We use this literal
-- instead of calling pgcrypto's crypt() at runtime, because some Supabase
-- projects don't have pgcrypto installed in the SQL Editor's search path.
-- gotrue accepts both $2a$ and $2b$ prefixes for verification, so this is
-- equivalent to what createUser() would produce.
--
-- Generated by: node -e "console.log(require('bcryptjs').hashSync('Welcome123!', 10))"
-- If you change v_temp_pw below, regenerate the hash with the same call and
-- paste it as v_pw_hash.
do $$
declare
  v_temp_pw   text    := 'Welcome123!';     -- edit if you want a different temp password
  v_pw_hash   text    := '$2b$10$yhukt3/f2KbmKEdApw4I8OyUdifFOHNoX9ObH5chD8iY3NlhPzpN.';
  v_email_dom text    := 'mmmis.vercel.app';    -- edit if your mess uses a different domain
  v_role_id   smallint;
  v_svc       text;
  v_email     text;
  v_auth_id   uuid;
  v_user_id   uuid;
  v_existing  uuid;
  v_count     integer := 0;
  v_seed      integer := 0;
  v_skipped   integer := 0;
  v_failed    integer := 0;

  -- The 45 members. (svc, rank, name) — corrected set per the admin.
  v_members constant jsonb := '[
    {"svc":"5083",   "rank":"LT",     "name":"H M KABONDE"},
    {"svc":"5337",   "rank":"2ND LT", "name":"R CHANNAH"},
    {"svc":"91611",  "rank":"WOI",    "name":"W MILUPI"},
    {"svc":"91964",  "rank":"WOI",    "name":"Y MUMBA"},
    {"svc":"97197",  "rank":"WOI",    "name":"J SEKELETU"},
    {"svc":"98685",  "rank":"WOII",   "name":"MUPEKA C"},
    {"svc":"98482",  "rank":"WOII",   "name":"HASENDE B"},
    {"svc":"98488",  "rank":"WOII",   "name":"JERE E"},
    {"svc":"98680",  "rank":"WOII",   "name":"MUNGILE H"},
    {"svc":"104797", "rank":"SGT",    "name":"BANDA S"},
    {"svc":"106641", "rank":"SGT",    "name":"SILUME K"},
    {"svc":"112324", "rank":"LCPL",   "name":"CHALWE G"},
    {"svc":"113312", "rank":"LCPL",   "name":"MAKUFELE I"},
    {"svc":"113963", "rank":"LCPL",   "name":"MWANSA K"},
    {"svc":"114278", "rank":"LCPL",   "name":"NYIWANGU I"},
    {"svc":"113436", "rank":"LCPL",   "name":"MFULA E"},
    {"svc":"113723", "rank":"LCPL",   "name":"MUNGUZA S"},
    {"svc":"112414", "rank":"LCPL",   "name":"CHIBUYE P"},
    {"svc":"98724",  "rank":"WOII",   "name":"MWANZA I J"},
    {"svc":"98875",  "rank":"SSGT",   "name":"TEMBO Z"},
    {"svc":"106759", "rank":"SGT",    "name":"TEMBO R"},
    {"svc":"112812", "rank":"LCPL",   "name":"JIKUBO I"},
    {"svc":"113956", "rank":"LCPL",   "name":"MWANSA N"},
    {"svc":"114685", "rank":"LCPL",   "name":"TEMBO S"},
    {"svc":"113975", "rank":"LCPL",   "name":"MWANZA E"},
    {"svc":"114619", "rank":"LCPL",   "name":"SIWALE A"},
    {"svc":"113137", "rank":"LCPL",   "name":"KHUMALO N"},
    {"svc":"98503",  "rank":"WOII",   "name":"KAJANI S"},
    {"svc":"105046", "rank":"SGT",    "name":"CHIRWA J"},
    {"svc":"105079", "rank":"SGT",    "name":"CHISHIMBA C"},
    {"svc":"112653", "rank":"LCPL",   "name":"CHOLA F"},
    {"svc":"113003", "rank":"LCPL",   "name":"KAPALU Y"},
    {"svc":"113569", "rank":"LCPL",   "name":"MUKOKILI F"},
    {"svc":"113868", "rank":"LCPL",   "name":"MUYUNDA I"},
    {"svc":"113980", "rank":"LCPL",   "name":"MWANZA J"},
    {"svc":"98479",  "rank":"WOII",   "name":"HAJILO M"},
    {"svc":"98684",  "rank":"WOII",   "name":"MUOMBO N"},
    {"svc":"106000", "rank":"SGT",    "name":"MUTALE JM"},
    {"svc":"112288", "rank":"LCPL",   "name":"BWALYA J S"},
    {"svc":"109136", "rank":"LCPL",   "name":"MUNAHAMBALA P"},
    {"svc":"112413", "rank":"LCPL",   "name":"CHIBUYE M"},
    {"svc":"113248", "rank":"LCPL",   "name":"LUNGU N"},
    {"svc":"113804", "rank":"LCPL",   "name":"MUSOPA M"},
    {"svc":"113326", "rank":"LCPL",   "name":"MALAMBO S B"},
    {"svc":"003678", "rank":"CE",     "name":"MR PHIRI A"}
  ]'::jsonb;

  v_member   jsonb;
  v_report   jsonb := '[]'::jsonb;
  v_orig     text;   -- full_name as supplied (kept verbatim in public.users)
  v_norm     text;   -- salutation-stripped, used for the first/last split
  v_first    text;
  v_last     text;
  v_sal_pos  integer;
begin
  -- 1. Member role id.
  select id into v_role_id from public.roles where code = 'member';
  if v_role_id is null then
    raise exception 'member role missing from public.roles (run 0001_init.sql first)';
  end if;

  -- 2. Bcrypt hash is pre-computed at the top of this block (v_pw_hash).
  --    We do NOT call pgcrypto here because the SQL Editor role may not
  --    have it on its search_path. The pre-computed $2b$10$... literal is
  --    equivalent to what auth.admin.createUser() would have produced.

  -- 3. Loop.
  for v_member in
    select * from jsonb_array_elements(v_members)
  loop
    v_svc    := v_member->>'svc';
    v_email  := ltrim(v_svc, '0') || '@' || v_email_dom;
    v_count  := v_count + 1;

    -- Skip if an active row already exists for this service_number.
    select id into v_user_id
      from public.users
     where service_number = v_svc
       and deleted_at is null
     limit 1;
    if v_user_id is not null then
      v_skipped := v_skipped + 1;
      v_report := v_report || jsonb_build_array(jsonb_build_object(
        'service_number', v_svc,
        'email',         v_email,
        'status',        'skipped_active',
        'user_id',       v_user_id,
        'message',       'public.users row already exists and is not deleted'
      ));
      continue;
    end if;

    -- Name split. We preserve the full string in `full_name` (the column
    -- that gets shown in the UI). For first_name / last_name we use a
    -- simple convention that matches the data shape:
    --   - Strip a leading salutation token (MR / MRS / MS / DR) if present.
    --   - first_name = first token of the remainder
    --   - last_name  = the rest of the tokens joined
    -- For military-roster entries ("MUPEKA C", "MWANSA K") this puts the
    -- surname in first_name and the initials in last_name. For Western-
    -- order entries ("H M KABONDE") it puts the first initial in first_name
    -- and the remainder in last_name. Either way the full_name column
    -- keeps the original spelling, and members can correct the split from
    -- /portal/profile if they need to.
    v_orig := coalesce(v_member->>'name', '');
    v_norm := btrim(regexp_replace(v_orig, '\s+', ' ', 'g'));
    v_sal_pos := case
      when v_norm ~* '^(MR|MRS|MS|DR)\s+' then 1
      else 0
    end;
    if v_sal_pos = 1 then
      v_norm := substring(v_norm from position(' ' in v_norm) + 1);
    end if;
    if position(' ' in v_norm) > 0 then
      v_first := split_part(v_norm, ' ', 1);
      v_last  := substring(v_norm from position(' ' in v_norm) + 1);
    else
      v_first := v_norm;
      v_last  := '';
    end if;

    -- Savepoint so a per-row failure doesn't roll back the whole batch.
    -- (The whole do $$ block is one transaction; we need SAVEPOINTs to
    -- isolate individual failures.)
    <<row>> begin
      -- Insert auth.users.
      begin
        insert into auth.users (
          instance_id,
          id,
          aud,
          role,
          email,
          encrypted_password,
          email_confirmed_at,
          raw_app_meta_data,
          raw_user_meta_data,
          created_at,
          updated_at,
          confirmation_token,
          email_change,
          email_change_token_new,
          recovery_token
        ) values (
          '00000000-0000-0000-0000-000000000000',
          -- Pure-SQL UUID generator so we don't need pgcrypto's
          -- gen_random_uuid(). Same RFC 4122 v4 format as gen_random_uuid().
          (
            substring(md5(random()::text || clock_timestamp()::text) for 8) || '-' ||
            substring(md5(random()::text || clock_timestamp()::text) for 4) || '-4' ||
            substring(substring(md5(random()::text) for 12) for 1) ||
            substring(substring(md5(random()::text) for 12) for 2) || '-' ||
            substring('89ab', 1 + (abs(hashtext(random()::text)) % 4)::int, 1) ||
            substring(md5(random()::text) for 3) || '-' ||
            substring(md5(random()::text) for 12)
          )::uuid,
          'authenticated',
          'authenticated',
          v_email,
          v_pw_hash,
          now(),
          jsonb_build_object('provider','email','providers', array['email']),
          jsonb_build_object(
            'service_number',  v_svc,
            'full_name',       v_orig,
            'rank',            v_member->>'rank'
          ),
          now(),
          now(),
          '',
          '',
          '',
          ''
        )
        returning id into v_auth_id;
      exception when others then
        v_failed := v_failed + 1;
        v_report := v_report || jsonb_build_array(jsonb_build_object(
          'service_number', v_svc,
          'email',         v_email,
          'status',        'failed',
          'user_id',       null,
          'message',       sqlerrm
        ));
        raise notice 'seed failed svc=% email=% err=%', v_svc, v_email, sqlerrm;
        return continue;  -- next iteration
      end;

      -- Insert public.users (explicit; doesn't depend on the trigger).
      begin
        insert into public.users (
          auth_id, service_number, full_name, email, role_id, rank,
          is_active
        ) values (
          v_auth_id, v_svc, v_orig, v_email, v_role_id, v_member->>'rank',
          true
        )
        returning id into v_user_id;
      exception when others then
        v_failed := v_failed + 1;
        v_report := v_report || jsonb_build_array(jsonb_build_object(
          'service_number', v_svc,
          'email',         v_email,
          'status',        'failed_public_users',
          'user_id',       null,
          'message',       sqlerrm
        ));
        -- Best-effort cleanup of the auth row.
        delete from auth.users where id = v_auth_id;
        raise notice 'seed failed_public_users svc=% email=% err=%', v_svc, v_email, sqlerrm;
        return continue;
      end;

      -- Insert public.members.
      begin
        insert into public.members (
          user_id, service_number, first_name, last_name, rank
        ) values (
          v_user_id, v_svc, v_first, v_last, v_member->>'rank'
        );
      exception when others then
        -- Soft-fail: keep public.users, just log the failure on the members row.
        v_report := v_report || jsonb_build_array(jsonb_build_object(
          'service_number', v_svc,
          'email',         v_email,
          'status',        'failed_members',
          'user_id',       v_user_id,
          'message',       'public.users ok, public.members failed: ' || sqlerrm
        ));
        v_failed := v_failed + 1;
        raise notice 'seed failed_members svc=% email=% err=%', v_svc, v_email, sqlerrm;
        return continue;
      end;

      v_seed := v_seed + 1;
      v_report := v_report || jsonb_build_array(jsonb_build_object(
        'service_number', v_svc,
        'email',         v_email,
        'status',        'seeded',
        'user_id',       v_user_id,
        'message',       'ok'
      ));
    end row;
  end loop;

  -- 4. Summary.
  raise notice '================================================================';
  raise notice '  MMMIS bulk member seed — done';
  raise notice '  total = %, seeded = %, skipped = %, failed = %',
               v_count, v_seed, v_skipped, v_failed;
  raise notice '  temp password = %', v_temp_pw;
  raise notice '================================================================';

  -- 5. Results table (visible in the SQL Editor "Results" panel).
  create temp table if not exists _seed_results (
    service_number text,
    email          text,
    status         text,
    user_id        uuid,
    message        text
  ) on commit drop;
  execute 'truncate table _seed_results';
  insert into _seed_results
  select
    (r->>'service_number')::text,
    (r->>'email')::text,
    (r->>'status')::text,
    nullif(r->>'user_id','')::uuid,
    r->>'message'
  from jsonb_array_elements(v_report) r;
end $$;

-- 6. Show the grid.
select * from _seed_results order by service_number;

-- 7. Quick "before / after" verification — re-runnable.
select
  (select count(*) from public.users  where email like '%@mess.zm.local' and deleted_at is null) as active_seeded_users,
  (select count(*) from public.members m
     join public.users u on u.id = m.user_id
    where u.email like '%@mess.zm.local' and u.deleted_at is null) as members_rows,
  (select count(*) from auth.users    where email like '%@mess.zm.local') as auth_users;

-- =============================================================================
-- Rollback (paste into SQL Editor if you want to undo the seed):
--
-- delete from public.members m
--   using public.users u
--  where m.user_id = u.id
--    and u.email like '%@mess.zm.local';
--
-- delete from public.users where email like '%@mess.zm.local';
--
-- delete from auth.users
--  where email like '%@mess.zm.local';
-- =============================================================================
