-- =============================================================================
-- 0023 — Bulk member seeding (Phase 23)
--
-- Admin-only one-shot path to onboard many mess members at once. The flow is:
--
--   1. Admin exports a CSV of (service_number, rank, name, salutation, email)
--      from bulk_members_template.csv (service_number, rank, name pre-filled;
--      admin may leave salutation blank and is NOT required to provide an
--      email).
--
--   2. Admin loads the staging table bulk_member_seed via COPY or a series of
--      INSERTs (the migration does not auto-populate; admin runs the COPY
--      statement in a separate SQL Editor query).
--
--   3. Admin invokes the bulk-seed-members Edge Function (service-role key),
--      which loops over the staging table and calls auth.admin.createUser
--      with raw_user_meta_data = { bulk_seed:'1', service_number, rank, name }.
--      That flag is picked up by fn_handle_new_auth_user() (extended below)
--      and a public.users + public.members row is materialised atomically.
--
--   4. Each member is created with email_confirm=true and an autogenerated
--      temporary password. If the CSV email cell was
--      blank, the Edge Function synthesises a placeholder "<svc>@<domain>"
--      so the auth.users unique constraint is satisfied; the member updates
--      their real email later from /portal/profile.
--
-- Idempotency:
--   - Staging table is wiped after the run.
--   - (service_number) is the partial unique key from migration 0020 — a
--     deactivated/soft-deleted row does NOT block a re-seed.
--   - If an active row already exists for that service_number the function
--     reports it as a SKIP and does not overwrite.
--
-- Dry-run:
--   - The Edge Function accepts ?dry_run=true which validates every row in
--     staging (parses name, computes the email-to-use including placeholder,
--     reports placeholder counts) without writing anything to auth.users or
--     public.*. Output is a JSON report.
-- =============================================================================

set search_path = public;

-- ---------------------------------------------------------------------------
-- 1. Staging table (admin-only, wiped after each run)
-- ---------------------------------------------------------------------------

create table if not exists public.bulk_member_seed (
  id              bigserial primary key,
  service_number  text        not null,
  rank            text,
  name            text        not null,
  salutation      text,                       -- 'MR', 'MRS', etc. (optional)
  email           text,
  status          text        not null default 'pending'
                              check (status in ('pending','seeded','skipped','failed')),
  message         text,
  created_user_id uuid,                       -- public.users.id once seeded
  created_at      timestamptz not null default now()
);

comment on table public.bulk_member_seed is
  'Admin-only staging table for bulk member onboarding. Populated from CSV, consumed by bulk-seed-members Edge Function, then truncated.';

-- Lock down. Only service role / SECURITY DEFINER RPCs touch this table.
alter table public.bulk_member_seed enable row level security;

drop policy if exists bulk_member_seed_admin_all on public.bulk_member_seed;
create policy bulk_member_seed_admin_all on public.bulk_member_seed
  for all to authenticated
  using      (public.is_administrator())
  with check (public.is_administrator());

-- ---------------------------------------------------------------------------
-- 2. Extend fn_handle_new_auth_user() to recognise the bulk_seed flag
-- ---------------------------------------------------------------------------
--
-- Existing trigger (0015) only fires on self_register='1'. We extend it so an
-- admin-driven bulk insert from the Edge Function materialises the public
-- rows the same way, with role='member'.

create or replace function public.fn_handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_meta      jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  v_selfreg   boolean := (v_meta->>'self_register') = '1';
  v_bulk      boolean := (v_meta->>'bulk_seed')     = '1';
  v_existing  uuid;
  v_role_id   smallint;
  v_user_id   uuid;
  v_svc       text;
  v_name      text;
  v_rank      text;
  v_first     text;
  v_last      text;
begin
  -- Only act on self-registrations or admin bulk-seeds.
  if not (v_selfreg or v_bulk) then
    return new;
  end if;

  -- If a public.users row already exists (e.g. admin pre-created the user)
  -- leave it alone.
  select id into v_existing from public.users where auth_id = new.id;
  if v_existing is not null then
    return new;
  end if;

  v_svc  := coalesce(nullif(v_meta->>'service_number', ''),
                     'ZM-' || substr(replace(new.id::text, '-', ''), 1, 6));
  v_name := coalesce(nullif(v_meta->>'full_name', ''),
                     split_part(new.email, '@', 1));
  v_rank := nullif(v_meta->>'rank', '');

  -- Split full name into first/last (best-effort). Trim the leading salutation
  -- token (e.g. "MR PHIRI A" -> first="PHIRI", last="A") if it matches.
  if v_name ~* '^(MR|MRS|MS|DR|CAPT|MAJ|COL|LT|LT COL|2LT|2ND LT|WO[ I]*|SGT|LCPL|SSGT|CE)\s+'
     and array_length(string_to_array(v_name, ' '), 1) >= 3 then
    v_first := split_part(v_name, ' ', 2);
    v_last  := substring(v_name from position(' ' in v_name) + 1);
    v_last  := substring(v_last from position(' ' in v_last) + 1);
  elsif position(' ' in v_name) > 0 then
    v_first := split_part(v_name, ' ', 1);
    v_last  := substring(v_name from position(' ' in v_name) + 1);
  else
    v_first := v_name;
    v_last  := '';
  end if;

  select id into v_role_id from public.roles where code = 'member';
  if v_role_id is null then
    raise exception 'member role missing from public.roles';
  end if;

  insert into public.users (
    auth_id, service_number, full_name, email, role_id, rank,
    is_active
  ) values (
    new.id, v_svc, v_name, new.email, v_role_id, v_rank,
    true
  )
  returning id into v_user_id;

  insert into public.members (
    user_id, service_number, first_name, last_name, rank
  ) values (
    v_user_id, v_svc, v_first, v_last, v_rank
  )
  on conflict (user_id) do nothing;

  -- For bulk seeds, also stamp the staging row as 'seeded'.
  if v_bulk then
    update public.bulk_member_seed
       set status = 'seeded',
           created_user_id = v_user_id,
           message = coalesce(message, '') || ' [trigger ' || extract(epoch from now())::text || ']'
     where service_number = v_svc
       and status = 'pending';
  end if;

  return new;
end;
$$;

-- The trigger itself already exists from 0015; nothing to recreate.
-- This migration is safe to run repeatedly because fn_handle_new_auth_user
-- is declared CREATE OR REPLACE.

-- ---------------------------------------------------------------------------
-- 3. Helper RPC: parse_name_for_bulk_seed(name text, salutation text)
-- ---------------------------------------------------------------------------
-- Pure function — does not touch any table. Useful for the Edge Function to
-- preview the first/last split before calling createUser.

create or replace function public.parse_name_for_bulk_seed(
  p_name        text,
  p_salutation  text default null
)
returns table (first_name text, last_name text, normalised_name text)
language sql
stable
as $$
  with cleaned as (
    select btrim(regexp_replace(coalesce(p_name, ''), '\s+', ' ', 'g')) as n
  ),
  stripped as (
    select case
      when n ~* '^(MR|MRS|MS|DR)\s+' and array_length(string_to_array(n, ' '), 1) >= 3
        then substring(n from position(' ' in n) + 1)
      when n ~* '^(MR|MRS|MS|DR)\s+' and array_length(string_to_array(n, ' '), 1) = 2
        then split_part(n, ' ', 2)
      else n
    end as n2
    from cleaned
  )
  select
    case
      when position(' ' in n2) > 0 then split_part(n2, ' ', 1)
      else n2
    end as first_name,
    case
      when position(' ' in n2) > 0 then substring(n2 from position(' ' in n2) + 1)
      else ''
    end as last_name,
    n2 as normalised_name
  from stripped;
$$;

-- ---------------------------------------------------------------------------
-- 4. Helper RPC: clear staging after a successful run
-- ---------------------------------------------------------------------------
-- Admin-only. Called by the Edge Function after the loop completes.

create or replace function public.bulk_member_seed_clear()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cleared integer;
begin
  if not public.is_administrator() then
    raise exception 'bulk_member_seed_clear requires administrator role';
  end if;
  delete from public.bulk_member_seed;
  get diagnostics v_cleared = row_count;
  return v_cleared;
end;
$$;

-- ---------------------------------------------------------------------------
-- 5. Audit: bulk seed writes one summary audit row at the end
-- ---------------------------------------------------------------------------
-- The Edge Function inserts a 'bulk_member_seed' row via the existing
-- public.audit_log table. No DB changes needed — the audit table already
-- accepts free-form action strings.
-- =============================================================================
